name: semux_mobile_wallet
description: A new Flutter application.

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  pm_curve25519: ^0.5.7

  pointycastle: ^1.0.2
  ed25519_hd_key: ^1.0.1
  ed25519: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
